set number
set matchpairs+=<:>
set showmatch
set smartindent
set autoindent
set termguicolors
set encoding=utf8
set tabstop=4
set shiftwidth=4
set expandtab
set modifiable
set clipboard=unnamed
